-- Migration: Add caller_guides and helper_guides tables
-- Created: 2025-11-15
-- Purpose: Store AI-generated guidance for callers and helpers

-- ============================================================================
-- CALLER GUIDES
-- ============================================================================

-- Caller Guides: AI-generated emergency response guidance for victims
-- Generated by: ResearchAgent + CallerGuideAgent pipeline
-- Contains: 3 bullet points with immediate actions while waiting for help
-- Example: "1. Move away from windows. 2. If smoke present, stay low. 3. Call out location every few minutes."
CREATE TABLE IF NOT EXISTS caller_guides (
    id SERIAL PRIMARY KEY,
    case_id INTEGER NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    guide_text TEXT NOT NULL, -- Markdown-formatted guidance (3 bullet points)
    research_query TEXT, -- The query used for Valyu search
    research_results_summary TEXT, -- Summary of search results used
    created_at TIMESTAMP DEFAULT NOW(),

    -- Ensure one guide per case (replace on regeneration)
    UNIQUE(case_id)
);

-- Index for fast lookup by case_id
CREATE INDEX IF NOT EXISTS idx_caller_guides_case_id ON caller_guides(case_id);

-- ============================================================================
-- HELPER GUIDES
-- ============================================================================

-- Helper Guides: AI-generated response guidance for helpers
-- Generated by: ResearchAgent + HelperGuideAgent pipeline
-- Contains: 3 bullet points with actionable steps for responders en route
-- Example: "1. Bring fire extinguisher if available. 2. Approach from north to avoid smoke. 3. Announce presence loudly before entering."
CREATE TABLE IF NOT EXISTS helper_guides (
    id SERIAL PRIMARY KEY,
    assignment_id INTEGER NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    guide_text TEXT NOT NULL, -- Markdown-formatted guidance (3 bullet points)
    research_query TEXT, -- The query used for Valyu search
    research_results_summary TEXT, -- Summary of search results used
    created_at TIMESTAMP DEFAULT NOW(),

    -- Ensure one guide per assignment (replace on regeneration)
    UNIQUE(assignment_id)
);

-- Index for fast lookup by assignment_id
CREATE INDEX IF NOT EXISTS idx_helper_guides_assignment_id ON helper_guides(assignment_id);

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE caller_guides IS 'AI-generated emergency response guidance for victims waiting for help';
COMMENT ON TABLE helper_guides IS 'AI-generated response guidance for helpers en route to assist';

COMMENT ON COLUMN caller_guides.guide_text IS 'Markdown-formatted guidance with 3 actionable bullet points';
COMMENT ON COLUMN caller_guides.research_query IS 'Query sent to Valyu search for context gathering';
COMMENT ON COLUMN caller_guides.research_results_summary IS 'Condensed summary of research results used to generate guidance';

COMMENT ON COLUMN helper_guides.guide_text IS 'Markdown-formatted guidance with 3 actionable steps for responders';
COMMENT ON COLUMN helper_guides.research_query IS 'Query sent to Valyu search for context gathering';
COMMENT ON COLUMN helper_guides.research_results_summary IS 'Condensed summary of research results used to generate guidance';
